app/blueprints/auth.py
import datetime
import logging
import uuid

from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from flask_login import login_user, login_required, logout_user, current_user
from itsdangerous import SignatureExpired, BadSignature

from app.auth import get_hashed_password, generate_token, confirm_token
from app.blueprints.forms import RegisterForm, LoginForm, ForgotPasswordForm, ResetPasswordForm
from app.blueprints.util import redirect_url
from app.db import db
from app.mail import send_confirmation_mail, send_password_reset_mail
from app.model import User

auth = Blueprint('auth', __name__)
log = logging.getLogger()


def perform_login(user, remember=False):
    # Create & store new session token
    user.session_token = uuid.uuid4().hex
    db.session.commit()

    # Login
    logged_in = login_user(user, remember)
    if logged_in:
        log.debug(f"Successfully logged in user {user} (remember_me={remember})")
    else:
        log.debug(f"Could not login user {user})")


@auth.route('/register', methods=['GET', 'POST'])
def register():
    # if already logged in, redirect to main page
    if current_user.is_authenticated:
        return redirect(redirect_url())

    # Register form: validate, create new user and redirect
    form = RegisterForm()
    if form.validate_on_submit():

        # Get form data
        email = form.email.data
        name = form.username.data
        hashed_password = get_hashed_password(form.password.data)

        # Create and add user
        user = User(email=email, name=name, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        log.debug(f"Added {user} to database")

        # Send confirmation link via email
        token = generate_token(email, current_app.config['SECRET_KEY'], current_app.config['SALT'])
        confirmation_url = url_for('auth.confirm_email', token=token, _external=True)
        send_confirmation_mail(name, email, confirmation_url)

        # Login user & redirect
        perform_login(user)
        return redirect(redirect_url('auth.unconfirmed'))

    return render_template('auth/register.html', form=form)


@auth.route('/confirm/<token>')
@login_required
def confirm_email(token):
    # Confirm the token (might be faulty or expired)
    email = None
    try:
        email = confirm_token(token, current_app.config['SECRET_KEY'], current_app.config['SALT'])
    except SignatureExpired as e:
        log.error(e)
    except BadSignature as e:
        log.error(e)

    if not email:
        pass    # TODO error occured

    # Confirm the user account
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        info_modal_title = "Account already confirmed"
        info_modal_body = "Your email address has already been confirmed."
    else:
        user.confirmed = datetime.datetime.now()
        db.session.commit()
        info_modal_title = "Confirmation successful"
        info_modal_body = "Great! Your email address was confirmed. Now you can start using the dashboard."

    return redirect(url_for('main.index', info_modal_title=info_modal_title, info_modal_body=info_modal_body))


@auth.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect(redirect_url())
    return render_template('auth/unconfirmed.html')


@auth.route('/confirm/resend')
@login_required
def resend_confirmation():
    name = current_user.name
    email = current_user.email

    # Send confirmation link via email
    token = generate_token(email, current_app.config['SECRET_KEY'], current_app.config['SALT'])
    confirmation_url = url_for('auth.confirm_email', token=token, _external=True)
    send_confirmation_mail(name, email, confirmation_url)
    return redirect(redirect_url('auth.unconfirmed'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    # if already logged in, redirect to main page
    if current_user.is_authenticated:
        return redirect(redirect_url())

    # Login form: validate, login via login_mngr and redirect
    form = LoginForm()
    if form.validate_on_submit():
        perform_login(form.user, form.remember_me.data)
        return redirect(redirect_url())

    return render_template('auth/login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    log.debug(f"Logged out user successfully")
    return redirect(redirect_url())


@auth.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first_or_404()

        # Generate a token
        token = generate_token(email, current_app.config['SECRET_KEY'], current_app.config['SALT'])
        reset_url = url_for('auth.reset_password', token=token, _external=True)
        send_password_reset_mail(user.name, email, reset_url)

        # Inform user about
        info_modal_title = "Password reset"
        info_modal_body = "An email with a link to reset your password has been send."
        return redirect(url_for('auth.login', info_modal_title=info_modal_title, info_modal_body=info_modal_body))

    return render_template('auth/forgot_password.html', form=form)


@auth.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    # Confirm the token (might be faulty or expired)
    email = None
    try:
        email = confirm_token(token, current_app.config['SECRET_KEY'], current_app.config['SALT'])
    except SignatureExpired as e:
        log.error(e)
    except BadSignature as e:
        log.error(e)

    if not email:
        pass  # TODO error occured

    user = User.query.filter_by(email=email).first_or_404()
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # update password for user
        user.password = get_hashed_password(form.password.data)
        db.session.commit()

        info_modal_title = "Password reset"
        info_modal_body = "Your password has been reset."
        return redirect(url_for('auth.login', info_modal_body=info_modal_body, info_modal_title=info_modal_title))

    return render_template('auth/reset_password.html', form=form)

app/blueprints/dashboard.py
import json
import logging
import os

from flask import Blueprint, render_template, url_for, request
from flask_login import login_required, current_user
from werkzeug.utils import redirect

from app.blueprints.forms import UploadDatasetForm
from app.blueprints.util import load_data, delete_data, get_clustering_info, _get_user_folder, redirect_url
from app.db import db
from app.decorators import confirmation_required
from app.model import Dataset
from app.util import ensure_exists_folder

dashboard = Blueprint('dashboard', __name__)
log = logging.getLogger()


@dashboard.route('/dashboard')
@login_required
@confirmation_required
def index():
    return render_template('dashboard/index.html')


@dashboard.route('/dashboard/datasets', methods=['GET', 'POST'])
@login_required
@confirmation_required
def datasets():
    # Upload form
    owner = current_user.id
    form = UploadDatasetForm(owner)
    if form.validate_on_submit():

        # Create dataset object from inputs
        # columns = pd.read_csv(f, header=0, nrows=0).columns.tolist()
        name = form.name.data
        description = form.description.data
        label_column = form.label_column.data
        prediction_column = form.prediction_column.data
        new_dataset = Dataset(name=name, owner=owner, description=description, label_column=label_column,
                              prediction_column=prediction_column)

        # Add dataset object to database
        db.session.add(new_dataset)
        db.session.commit()
        log.debug(f"Added {new_dataset} to database")

        # Ensure user has an upload folder already
        user_folder = _get_user_folder(owner)
        ensure_exists_folder(user_folder)

        # Save data file in user_folder
        f = form.dataset.data
        file_path = os.path.join(user_folder, new_dataset.id + '.csv')
        f.seek(0)  # to avoid storing an empty file
        f.save(file_path)
        if not os.path.exists(file_path):
            db.session.delete(new_dataset)
            db.session.commit()
            return redirect(url_for('dashboard.datasets', info_modal_title='An error occurred',
                                    info_modal_body='Could not save your dataset!'))

        # Redirect to same page (to clear form inputs)
        return redirect(url_for('dashboard.datasets'))

    # Get all the user's datasets
    dataset_list = Dataset.query.filter_by(owner=owner)

    return render_template('dashboard/datasets.html', form=form, datasets=dataset_list)


@dashboard.route('/dashboard/datasets/delete', methods=['POST'])
@login_required
@confirmation_required
def delete_dataset():
    # Get selected datasets
    owner = current_user.id
    selected_names = json.loads(request.form.get('datasets'))
    selected_datasets = Dataset.query.filter_by(owner=owner).filter(Dataset.name.in_(selected_names)).all()
    for d in selected_datasets:
        delete_data(owner, d)
    return redirect(redirect_url('dashboard.datasets'))


@dashboard.route('/dashboard/inspect', methods=['GET', 'POST'])
@login_required
@confirmation_required
def inspect():
    # Either get dataset from request via name (POST) or simply the latest uploaded (GET)
    selected_name = request.form.get('dataset')
    all_datasets = Dataset.query.filter_by(owner=current_user.id).order_by(Dataset.upload_date.desc()).all()

    dataset = None
    if selected_name is None:
        # Most recent uploaded (first in list)
        if len(all_datasets) > 0:
            dataset = all_datasets[0]
        else:
            return redirect(url_for('dashboard.datasets', info_modal_title="No datasets found",
                                    info_modal_body="You have to upload a dataset first."))
    else:
        # Get dataset by name
        for d in all_datasets:
            if d.name == selected_name:
                dataset = d
        # Abort if dataset name does not match any of the datasets
        if not dataset:
            return redirect(url_for('dashboard.datasets', info_modal_title="Selected dataset not found",
                                    info_modal_body=f"Couldn't find a dataset named {selected_name}."))

    # Load data columns+types (cached)
    columns = load_data(current_user.id, dataset.id).dtypes  # TODO try catch
    # log.debug(f"{type(columns)}: {columns}")

    return render_template('dashboard/inspect.html', all_datasets=all_datasets, dataset=dataset, columns=columns)


@dashboard.route('/dashboard/datasets/<name>')
@login_required
@confirmation_required
def raw_data(name):
    # Get query parameters limit, offset, sort, order and filter TODO check for valid inputs?
    # log.debug(request.args)
    offset = request.args.get('offset')  # might be None
    offset = int(offset) if offset else 0  # parse str to int or 0 if None
    limit = request.args.get('limit')
    limit = int(limit) if limit else 10
    sort = request.args.get('sort')
    order = request.args.get('order')
    filter = request.args.get('filter')

    # Query dataset object from database and load data
    d = Dataset.query.filter_by(owner=current_user.id, name=name).first_or_404()
    data = load_data(current_user.id, d.id)  # TODO try catch

    # Apply filter
    if filter:
        log.debug(f"Filter {filter} {type(filter)}")
        filter = json.loads(filter)
        log.debug(f"Filter {filter} {type(filter)}")
        for c, f in filter.items():
            data = data[data[c].astype(str).str.contains(f)]

    # Paginate & sort loaded data
    total_rows = len(data)
    if sort and order:
        data = data.sort_values(by=sort, ascending=(order == 'asc'))
    data = data.iloc[offset:offset + limit]

    # Prepare json from dataframe
    data_json = data.to_json(orient='records')
    parsed = json.loads(data_json)  # list of records (dicts with column:value pairs)

    # server-side pagination requires format {'total': num, 'rows': {... dataframe ...}}
    server_side_format = {'total': total_rows, 'rows': parsed}

    return json.dumps(server_side_format, indent=4)


@dashboard.route('/dashboard/datasets/columns')
@login_required
@confirmation_required
def raw_data_columns():
    id = request.args.get('id')  # might be None
    d = Dataset.query.filter_by(owner=current_user.id, id=id).first_or_404()
    columns = load_data(current_user.id, d.id).dtypes
    columns = columns.drop([d.label_column, d.prediction_column])
    return columns.to_json(default_handler=str)  # default handler to fix recursion OverflowError


@dashboard.route('/dashboard/datasets/sizes')
@login_required
@confirmation_required
def raw_data_sizes():
    all_datasets = Dataset.query.filter_by(owner=current_user.id).order_by(Dataset.name).all()
    if len(all_datasets) <= 0:
        return redirect(url_for('dashboard.datasets', info_modal_title="No datasets found",
                                info_modal_body="You have to upload a dataset first."))
    # Return sizes of all datasets
    return {d.id: len(load_data(current_user.id, d.id)) for d in all_datasets}


@dashboard.route('/dashboard/fairness')
@login_required
@confirmation_required
def fairness():
    # Get all the user's datasets
    all_datasets = Dataset.query.filter_by(owner=current_user.id).order_by(Dataset.name).all()
    if len(all_datasets) <= 0:
        return redirect(url_for('dashboard.datasets', info_modal_title="No datasets found",
                                info_modal_body="You have to upload a dataset first."))
    return render_template('dashboard/fairness.html', all_datasets=all_datasets)


@dashboard.route('/dashboard/clustering')
@confirmation_required
def clustering_info():
    return get_clustering_info()

app/blueprints/task.py
import logging
import math

from flask import Blueprint, jsonify, request, url_for, abort
from flask_login import login_required, current_user
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.cluster.xmeans import xmeans
from sklearn.cluster import KMeans

from app.blueprints.util import load_data, get_param_dict
from app.decorators import confirmation_required
from app.model import Dataset
from app.tasks import fairness_analysis, FairnessTask

task = Blueprint('task', __name__)
log = logging.getLogger()


@task.route('/task/fairness', methods=['POST'])
@login_required
@confirmation_required
def start_fairness_task():
    # Does the user already have a running task? If so, stop it before starting another
    stopped = FairnessTask.stop(current_user)
    log.debug(f"Stopped current task? {stopped}")

    # Get data from request body
    dataset_id = request.form.get("dataset_id")  # TODO no dataset id in request body
    pos_label = int(request.form.get("positive_class"))
    threshold = float(request.form.get("threshold"))
    categ_columns = request.form.getlist("categ_columns[]")
    if not categ_columns:  # If not provided, set to None
        categ_columns = None

    algorithm = request.form.get("algorithm", type=str)
    parameters = request.form.getlist("parameters[]")
    values = request.form.getlist("values[]")
    estimate_k = request.form.get("estimate_k")
    if estimate_k == "true":
        estimate_k = True
    else:
        estimate_k = False
    param_dict = get_param_dict(algorithm, parameters, values)
    log.debug(f"{param_dict}")

    # Load data & serialize
    data = load_data(current_user.id, dataset_id)
    data_json = data.to_json()  # json serialization is required to send task

    # Start task
    dataset = Dataset.query.get(dataset_id)
    t = fairness_analysis.delay(data_json, algorithm, pos_label=pos_label, threshold=threshold,
                                categ_columns=categ_columns, label_column=dataset.label_column,
                                prediction_column=dataset.prediction_column, param_dict=param_dict,
                                estimate_k=estimate_k)
    FairnessTask.cache(current_user, t.id)  # cache running task

    return jsonify({}), 202, {'status': url_for('task.status')}


@task.route('/task/fairness/status')
@login_required
@confirmation_required
def status():
    # Is there a current task?
    current_task_id = FairnessTask.get(current_user)
    if current_task_id is None:
        return abort(404)

    # Switch task state
    t = fairness_analysis.AsyncResult(current_task_id)
    if t.state == 'PENDING':
        # job did not start yet
        response = {
            'state': t.state,
            'status': 'Waiting for task to start...'
        }
    elif t.state == 'PROGRESS':
        response = {
            'state': t.state,
            'status': t.info.get('status', '')  # task.info is a dict
        }
    elif t.state == 'SUCCESS':
        response = {
            'state': t.state,
            'status': 'Successfully finished task!',
            'result': t.info  # task.info is a json string (result)
        }
        FairnessTask.delete(current_user)  # remove cache entry
    else:
        # something went wrong in the background job (states: FAILURE, RETRY, REVOKED)
        response = {
            'state': t.state,
            'status': str(t.info),  # this is the exception raised
        }
        # FairnessTask.delete(current_user)  # remove cache entry????

    return jsonify(response)  # TODO return stream

app/templates/dashboard/dashboard_base.html
{%- extends "base.html" %}

{% block title %}Dashboard{% endblock %}

<!-- Styles -->
{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='css/sidebars.css') }}" rel="stylesheet">
{% endblock %}


<!-- No navbar here but a side bar instead -->
{% block navbar %}
{% endblock %}


<!-- Content -->
{% block content %}

<div class="container-fluid p-0">
    <main class="main">
        <div class="d-flex flex-column bg-light sidebar">
            <a href="{{ url_for('main.index') }}" class="d-block p-3 link-dark text-decoration-none border-bottom"
               style="margin-top: -5px;">
                <img src="{{ url_for('static', filename='logo.png') }}" width="40" height="40">
                <span class="visually-hidden">Icon-only</span>
            </a>
            <ul class="nav nav-pills nav-flush flex-column mb-auto text-center" id="navList">
                <li class="nav-item">
                    <a href="{{ url_for('dashboard.index') }}" class="nav-link py-3 border-bottom"
                       aria-current="page"
                       title="Home"
                       data-bs-toggle="tooltip" data-bs-placement="right">
                        <svg class="bi" width="24" height="24" role="img" aria-label="Home">
                            <use xlink:href="#home"/>
                        </svg>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('dashboard.datasets') }}" class="nav-link py-3 border-bottom"
                       title="Datasets"
                       data-bs-toggle="tooltip"
                       data-bs-placement="right">
                        <svg class="bi" width="24" height="24" role="img" aria-label="Datasets">
                            <use xlink:href="#upload"/>
                        </svg>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('dashboard.inspect') }}" class="nav-link py-3 border-bottom" title="Inspect"
                       data-bs-toggle="tooltip"
                       data-bs-placement="right">
                        <svg class="bi" width="24" height="24" role="img" aria-label="Inspect">
                            <use xlink:href="#table"/>
                        </svg>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('dashboard.fairness') }}" class="nav-link py-3 border-bottom"
                       title="Dashboard" data-bs-toggle="tooltip"
                       data-bs-placement="right">
                        <svg class="bi" width="24" height="24" role="img" aria-label="Fairness">
                            <use xlink:href="#speedometer2"/>
                        </svg>
                    </a>
                </li>
            </ul>
            <div class="dropdown border-top">
                <a href="#"
                   class="d-flex align-items-center justify-content-center p-3 dropdown-toggle-color
                   text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    <svg class="bi" width="24" height="24" role="img" aria-label="Customers">
                        <use xlink:href="#people-circle"/>
                    </svg>
                </a>
                <ul class="dropdown-menu text-small shadow custom-drop" aria-labelledby="dropdownUser">
                    <li><a class="dropdown-item" href="{{ url_for('dashboard.datasets') }}">Manage datasets</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('dashboard.fairness') }}">Subgroup fairness</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.profile') }}">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Sign out</a></li>
                </ul>
            </div>
        </div>


        <!--        <div class="col-md-10 col-lg-11">-->
        <div class="p-3 dashboard-content">
            {% block inner_content %}
            {% endblock %}
        </div>
        <!--        </div>-->


    </main>

</div>


{% endblock %}


{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/sidebars.js') }}"></script>
{% endblock %}

app/templates/dashboard/fairness.html
{% extends "dashboard/dashboard_base.html" %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='css/fairness.css') }}" rel="stylesheet">
{% endblock %}}


{% block inner_content %}
<form class="border rounded shadow px-3" id="fairness-form">
    <h1 class="h2">Subgroup Fairness Analysis</h1>
    <div class="row p-2 gx-5 gy-3">

        <!-- Dataset selectpicker -->
        <div class="col col-1">
            <label for="dataset-select" class="form-label col-form-label-lg">Dataset:</label>
        </div>
        <div class="col col-2 offset-1">
            <select class="selectpicker" id="dataset-select" name="dataset" data-live-search="true"
                    title="Choose a dataset..." required>
                {% for d in all_datasets %}
                <option value="{{ d.id }}">{{ d.name }}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                Please select a dataset.
            </div>
        </div>

        <!-- Positive class switch -->
        <div class="col col-3 offset-1 form-check form-switch form-control-lg">
            <input class="form-check-input" type="checkbox" role="switch" id="switch">
            <label class="form-check-label" for="switch">Positive class label: 0</label>
        </div>

        <!-- Entropy threshold slider -->
        <div class="col col-3">
            <label for="threshold" class="form-label col-form-label-lg">Entropy threshold: 0.65</label>
            <input type="range" class="form-range" min="0" max="1" step="0.01" value="0.65" id="threshold">
        </div>

        <!-- Categorical columns multi selectpicker-->
        <div class="col col-2">
            <label for="select-categ" class="form-label col-form-label-lg">Categorical columns:</label>
        </div>
        <div class="col col-2">
            <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus"
                  data-bs-content="Select a dataset first!" id="popover-categ">
                <select class="selectpicker" id="select-categ" data-actions-box="true"
                        title="Categorical columns ..." data-selected-text-format="count" multiple disabled>
                </select>
            </span>
        </div>

        <!-- Clustering algorithm selectpicker -->
        <div class="col col-2">
            <label for="select-algo" class="form-label col-form-label-lg">Clustering algorithm:</label>
        </div>
        <div class="col col-2">
            <select class="selectpicker" id="select-algo" data-live-search="true"
                    title="Choose a clustering ...">
            </select>
        </div>

        <!-- Algorithm parameters + Modal -->
        <div class="col col-3 offset-1">
            <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus"
                  data-bs-content="Select an algorithm first!" id="popover-params">
                <button type="button" class="btn btn-lg btn-danger" data-bs-toggle="modal"
                        data-bs-target="#parameter-modal" id="parameter-button" disabled>
                    <svg class="bi" width="20" height="20" role="img" aria-label="Home">
                        <use xlink:href="#sliders-vertical"/>
                    </svg>
                    Algorithm parameters
                </button>
            </span>
        </div>

        <div class="modal fade" id="parameter-modal" tabindex="-1" aria-labelledby="parameter-modal-label"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="parameter-modal-label">Parameters</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="parameter-modal-body">
                        ... Parameters ...
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-danger" id="parameter-clear">
                            <svg class="bi" width="16" height="16">
                                <use xlink:href="#trash-fill"></use>
                            </svg>
                            Clear All
                        </button>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <!-- Evaluation buttons -->
    <div class="d-flex mt-4 mb-3">
        <input class="btn btn-lg btn-primary w-25 ms-auto me-auto" id="task-auto-submit" name="submit" type="button"
               value="Automatic Evaluation">
        <input class="btn btn-lg btn-primary w-25 me-auto" id="task-submit" name="submit" type="button"
               value="Manual Evaluation"/>
    </div>
</form>


<div class="row my-1">
    <div class="alert alert-info" id="task-status" role="alert" style="display: none;">
        Display progress information
    </div>
</div>

<div id="chart-area" class="chart-area" style="display: none">
    <div class="row gy-4 gx-3">
        <div class="col col-6">
            <div class="border rounded shadow p-0">
                <div class="chart-container">
                    <canvas id="chart-fair"></canvas>
                    <button id="chart-fair-export">Export PDF</button>
                </div>
            </div>
        </div>

        <div class="col col-6">
            <div class="border rounded shadow p-0">
                <div class="overflow-x-auto">
                    <div class="chart-container">
                        <canvas id="chart-group"></canvas>
                    </div>
                </div>
            </div>

        </div>

        <div class="col col-12">
            <div class="border rounded shadow p-0">
                <table id="table-groups"
                       data-pagination="true"
                       data-page-list="[5, 10, 25, 50, all]"
                       data-detail-view="true"
                       data-detail-view-by-click="true"
                       data-height="500">
                </table>
            </div>
        </div>

        <div class="col col-6">
            <div class="border rounded shadow p-0">
                <div class="chart-container">
                    <canvas id="chart-select"></canvas>
                </div>
            </div>
        </div>

        <div class="col col-6">
            <div class="border rounded shadow p-0">
                <div class="row p-2 gx-5" id="ranking-config">
                    <select class="selectpicker col col-6" id="select-ranking" data-width="50%">
                        <option value="c_stat_par">Cluster statistical parity</option>
                        <option value="c_eq_opp">Cluster equal opportunity</option>
                        <option value="c_avg_odds">Cluster avg. equalized odds</option>
                        <option value="c_acc">Cluster accuracy</option>
                        <option value="g_stat_par">Subgroup statistical parity</option>
                        <option value="g_eq_opp">Subgroup equal opportunity</option>
                        <option value="g_avg_odds">Subgroup avg. equalized odds</option>
                        <option value="g_acc">Subgroup accuracy</option>
                    </select>
                    <div class="col col-6 form-check form-switch col-form-label-lg">
                        <input class="form-check-input" type="checkbox" role="switch" id="switch-ranking-order">
                        <label class="form-check-label" for="switch-ranking-order">Ascending</label>
                    </div>
                </div>
                <div class="chart-container">
                    <canvas id="chart-ranking"></canvas>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}


{% block scripts %}
{{ super() }}
<script>
    const start_task_url = JSON.parse('{{ url_for("task.start_fairness_task") | tojson }}')
    const clustering_info_url = JSON.parse('{{ url_for("dashboard.clustering_info") | tojson }}')
    const columns_info_url = JSON.parse('{{ url_for("dashboard.raw_data_columns") | tojson }}')
</script>
<script src="{{ url_for('static', filename='js/fairness.js') }}"></script>
{% endblock %}