app/blueprints/auth.py
import datetime
import logging
import uuid

from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from flask_login import login_user, login_required, logout_user, current_user
from itsdangerous import SignatureExpired, BadSignature

from app.auth import get_hashed_password, generate_token, confirm_token
from app.blueprints.forms import RegisterForm, LoginForm, ForgotPasswordForm, ResetPasswordForm
from app.blueprints.util import redirect_url
from app.db import db
from app.mail import send_confirmation_mail, send_password_reset_mail
from app.model import User

auth = Blueprint('auth', __name__)
log = logging.getLogger()


def perform_login(user, remember=False):
    # Create & store new session token
    user.session_token = uuid.uuid4().hex
    db.session.commit()

    # Login
    logged_in = login_user(user, remember)
    if logged_in:
        log.debug(f"Successfully logged in user {user} (remember_me={remember})")
    else:
        log.debug(f"Could not login user {user})")


@auth.route('/register', methods=['GET', 'POST'])
def register():
    # if already logged in, redirect to main page
    if current_user.is_authenticated:
        return redirect(redirect_url())

    # Register form: validate, create new user and redirect
    form = RegisterForm()
    if form.validate_on_submit():

        # Get form data
        email = form.email.data
        name = form.username.data
        hashed_password = get_hashed_password(form.password.data)

        # Create and add user
        user = User(email=email, name=name, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        log.debug(f"Added {user} to database")

        # Send confirmation link via email
        token = generate_token(email, current_app.config['SECRET_KEY'], current_app.config['SALT'])
        confirmation_url = url_for('auth.confirm_email', token=token, _external=True)
        send_confirmation_mail(name, email, confirmation_url)

        # Login user & redirect
        perform_login(user)
        return redirect(redirect_url('auth.unconfirmed'))

    return render_template('auth/register.html', form=form)


@auth.route('/confirm/<token>')
@login_required
def confirm_email(token):
    # Confirm the token (might be faulty or expired)
    email = None
    try:
        email = confirm_token(token, current_app.config['SECRET_KEY'], current_app.config['SALT'])
    except SignatureExpired as e:
        log.error(e)
    except BadSignature as e:
        log.error(e)

    if not email:
        pass    # TODO error occured

    # Confirm the user account
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        info_modal_title = "Account already confirmed"
        info_modal_body = "Your email address has already been confirmed."
    else:
        user.confirmed = datetime.datetime.now()
        db.session.commit()
        info_modal_title = "Confirmation successful"
        info_modal_body = "Great! Your email address was confirmed. Now you can start using the dashboard."

    return redirect(url_for('main.index', info_modal_title=info_modal_title, info_modal_body=info_modal_body))


@auth.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect(redirect_url())
    return render_template('auth/unconfirmed.html')


@auth.route('/confirm/resend')
@login_required
def resend_confirmation():
    name = current_user.name
    email = current_user.email

    # Send confirmation link via email
    token = generate_token(email, current_app.config['SECRET_KEY'], current_app.config['SALT'])
    confirmation_url = url_for('auth.confirm_email', token=token, _external=True)
    send_confirmation_mail(name, email, confirmation_url)
    return redirect(redirect_url('auth.unconfirmed'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    # if already logged in, redirect to main page
    if current_user.is_authenticated:
        return redirect(redirect_url())

    # Login form: validate, login via login_mngr and redirect
    form = LoginForm()
    if form.validate_on_submit():
        perform_login(form.user, form.remember_me.data)
        return redirect(redirect_url())

    return render_template('auth/login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    log.debug(f"Logged out user successfully")
    return redirect(redirect_url())


@auth.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first_or_404()

        # Generate a token
        token = generate_token(email, current_app.config['SECRET_KEY'], current_app.config['SALT'])
        reset_url = url_for('auth.reset_password', token=token, _external=True)
        send_password_reset_mail(user.name, email, reset_url)

        # Inform user about
        info_modal_title = "Password reset"
        info_modal_body = "An email with a link to reset your password has been send."
        return redirect(url_for('auth.login', info_modal_title=info_modal_title, info_modal_body=info_modal_body))

    return render_template('auth/forgot_password.html', form=form)


@auth.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    # Confirm the token (might be faulty or expired)
    email = None
    try:
        email = confirm_token(token, current_app.config['SECRET_KEY'], current_app.config['SALT'])
    except SignatureExpired as e:
        log.error(e)
    except BadSignature as e:
        log.error(e)

    if not email:
        pass  # TODO error occured

    user = User.query.filter_by(email=email).first_or_404()
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # update password for user
        user.password = get_hashed_password(form.password.data)
        db.session.commit()

        info_modal_title = "Password reset"
        info_modal_body = "Your password has been reset."
        return redirect(url_for('auth.login', info_modal_body=info_modal_body, info_modal_title=info_modal_title))

    return render_template('auth/reset_password.html', form=form)

app/blueprints/dashboard.py
import json
import logging
import os

from flask import Blueprint, render_template, url_for, request
from flask_login import login_required, current_user
from werkzeug.utils import redirect

from app.blueprints.forms import UploadDatasetForm
from app.blueprints.util import load_data, delete_data, get_clustering_info, _get_user_folder, redirect_url
from app.db import db
from app.decorators import confirmation_required
from app.model import Dataset
from app.util import ensure_exists_folder

dashboard = Blueprint('dashboard', __name__)
log = logging.getLogger()


@dashboard.route('/dashboard')
@login_required
@confirmation_required
def index():
    return render_template('dashboard/index.html')


@dashboard.route('/dashboard/datasets', methods=['GET', 'POST'])
@login_required
@confirmation_required
def datasets():
    # Upload form
    owner = current_user.id
    form = UploadDatasetForm(owner)
    if form.validate_on_submit():

        # Create dataset object from inputs
        # columns = pd.read_csv(f, header=0, nrows=0).columns.tolist()
        name = form.name.data
        description = form.description.data
        label_column = form.label_column.data
        prediction_column = form.prediction_column.data
        new_dataset = Dataset(name=name, owner=owner, description=description, label_column=label_column,
                              prediction_column=prediction_column)

        # Add dataset object to database
        db.session.add(new_dataset)
        db.session.commit()
        log.debug(f"Added {new_dataset} to database")

        # Ensure user has an upload folder already
        user_folder = _get_user_folder(owner)
        ensure_exists_folder(user_folder)

        # Save data file in user_folder
        f = form.dataset.data
        file_path = os.path.join(user_folder, new_dataset.id + '.csv')
        f.seek(0)  # to avoid storing an empty file
        f.save(file_path)
        if not os.path.exists(file_path):
            db.session.delete(new_dataset)
            db.session.commit()
            return redirect(url_for('dashboard.datasets', info_modal_title='An error occurred',
                                    info_modal_body='Could not save your dataset!'))

        # Redirect to same page (to clear form inputs)
        return redirect(url_for('dashboard.datasets'))

    # Get all the user's datasets
    dataset_list = Dataset.query.filter_by(owner=owner)

    return render_template('dashboard/datasets.html', form=form, datasets=dataset_list)


@dashboard.route('/dashboard/datasets/delete', methods=['POST'])
@login_required
@confirmation_required
def delete_dataset():
    # Get selected datasets
    owner = current_user.id
    selected_names = json.loads(request.form.get('datasets'))
    selected_datasets = Dataset.query.filter_by(owner=owner).filter(Dataset.name.in_(selected_names)).all()
    for d in selected_datasets:
        delete_data(owner, d)
    return redirect(redirect_url('dashboard.datasets'))


@dashboard.route('/dashboard/inspect', methods=['GET', 'POST'])
@login_required
@confirmation_required
def inspect():
    # Either get dataset from request via name (POST) or simply the latest uploaded (GET)
    selected_name = request.form.get('dataset')
    all_datasets = Dataset.query.filter_by(owner=current_user.id).order_by(Dataset.upload_date.desc()).all()

    dataset = None
    if selected_name is None:
        # Most recent uploaded (first in list)
        if len(all_datasets) > 0:
            dataset = all_datasets[0]
        else:
            return redirect(url_for('dashboard.datasets', info_modal_title="No datasets found",
                                    info_modal_body="You have to upload a dataset first."))
    else:
        # Get dataset by name
        for d in all_datasets:
            if d.name == selected_name:
                dataset = d
        # Abort if dataset name does not match any of the datasets
        if not dataset:
            return redirect(url_for('dashboard.datasets', info_modal_title="Selected dataset not found",
                                    info_modal_body=f"Couldn't find a dataset named {selected_name}."))

    # Load data columns+types (cached)
    columns = load_data(current_user.id, dataset.id).dtypes  # TODO try catch
    # log.debug(f"{type(columns)}: {columns}")

    return render_template('dashboard/inspect.html', all_datasets=all_datasets, dataset=dataset, columns=columns)


@dashboard.route('/dashboard/datasets/<name>')
@login_required
@confirmation_required
def raw_data(name):
    # Get query parameters limit, offset, sort, order and filter TODO check for valid inputs?
    # log.debug(request.args)
    offset = request.args.get('offset')  # might be None
    offset = int(offset) if offset else 0  # parse str to int or 0 if None
    limit = request.args.get('limit')
    limit = int(limit) if limit else 10
    sort = request.args.get('sort')
    order = request.args.get('order')
    filter = request.args.get('filter')

    # Query dataset object from database and load data
    d = Dataset.query.filter_by(owner=current_user.id, name=name).first_or_404()
    data = load_data(current_user.id, d.id)  # TODO try catch

    # Apply filter
    if filter:
        log.debug(f"Filter {filter} {type(filter)}")
        filter = json.loads(filter)
        log.debug(f"Filter {filter} {type(filter)}")
        for c, f in filter.items():
            data = data[data[c].astype(str).str.contains(f)]

    # Paginate & sort loaded data
    total_rows = len(data)
    if sort and order:
        data = data.sort_values(by=sort, ascending=(order == 'asc'))
    data = data.iloc[offset:offset + limit]

    # Prepare json from dataframe
    data_json = data.to_json(orient='records')
    parsed = json.loads(data_json)  # list of records (dicts with column:value pairs)

    # server-side pagination requires format {'total': num, 'rows': {... dataframe ...}}
    server_side_format = {'total': total_rows, 'rows': parsed}

    return json.dumps(server_side_format, indent=4)


@dashboard.route('/dashboard/datasets/columns')
@login_required
@confirmation_required
def raw_data_columns():
    id = request.args.get('id')  # might be None
    d = Dataset.query.filter_by(owner=current_user.id, id=id).first_or_404()
    columns = load_data(current_user.id, d.id).dtypes
    columns = columns.drop([d.label_column, d.prediction_column])
    return columns.to_json(default_handler=str)  # default handler to fix recursion OverflowError


@dashboard.route('/dashboard/datasets/sizes')
@login_required
@confirmation_required
def raw_data_sizes():
    all_datasets = Dataset.query.filter_by(owner=current_user.id).order_by(Dataset.name).all()
    if len(all_datasets) <= 0:
        return redirect(url_for('dashboard.datasets', info_modal_title="No datasets found",
                                info_modal_body="You have to upload a dataset first."))
    # Return sizes of all datasets
    return {d.id: len(load_data(current_user.id, d.id)) for d in all_datasets}


@dashboard.route('/dashboard/fairness')
@login_required
@confirmation_required
def fairness():
    # Get all the user's datasets
    all_datasets = Dataset.query.filter_by(owner=current_user.id).order_by(Dataset.name).all()
    if len(all_datasets) <= 0:
        return redirect(url_for('dashboard.datasets', info_modal_title="No datasets found",
                                info_modal_body="You have to upload a dataset first."))
    return render_template('dashboard/fairness.html', all_datasets=all_datasets)


@dashboard.route('/dashboard/clustering')
@confirmation_required
def clustering_info():
    return get_clustering_info()

app/blueprints/main.py
import logging

from flask import Blueprint, render_template, url_for, redirect
from flask_login import login_required, current_user

from app.auth import get_hashed_password
from app.blueprints.forms import ChangePasswordForm, PasswordConfirmationForm
from app.blueprints.util import get_user_quota, delete_all_datasets, delete_user_account
from app.db import db

main = Blueprint('main', __name__)
log = logging.getLogger()


# a simple page that says hello & sends a mail (blocked by testing)
@main.route('/')
def index():
    return render_template('index.html')


@main.route('/test')
def test():
    return render_template('mail/confirmation.html')


@main.route('/profile')
@login_required
def profile():
    form = ChangePasswordForm(current_user.id)
    con_form_dataset = PasswordConfirmationForm(current_user.id, 'password_dataset')
    con_form_account = PasswordConfirmationForm(current_user.id, 'password_account')
    return render_template('profile.html', form=form, con_form_dataset=con_form_dataset,
                           con_form_account=con_form_account)


@main.route('/profile/change_password', methods=['POST'])
@login_required
def change_password():
    form = ChangePasswordForm(current_user.id)
    con_form_dataset = PasswordConfirmationForm(current_user.id, 'password_dataset', was_submitted=False)
    con_form_account = PasswordConfirmationForm(current_user.id, 'password_account', was_submitted=False)

    if form.validate_on_submit():
        # set new password
        current_user.password = get_hashed_password(form.new_password.data)
        db.session.commit()

        # redirect to profile page with modal for successful password update
        return redirect(url_for('main.profile', info_modal_title="Password changed",
                                info_modal_body="Your password has successfully been updated!"))

    return render_template('profile.html', form=form, con_form_dataset=con_form_dataset,
                           con_form_account=con_form_account)


@main.route('/profile/delete_datasets', methods=['POST'])
@login_required
def delete_datasets():
    form = ChangePasswordForm(current_user.id, was_submitted=False)
    con_form_dataset = PasswordConfirmationForm(current_user.id, 'password_dataset')
    con_form_account = PasswordConfirmationForm(current_user.id, 'password_account', was_submitted=False)

    # Delete all datasets password confirmation
    if con_form_dataset.validate_on_submit():
        delete_all_datasets(current_user.id)
        return redirect(url_for('main.profile', info_modal_title="Deleted All Datasets",
                                info_modal_body="Your datasets were deleted."))

    return render_template('profile.html', form=form, con_form_dataset=con_form_dataset,
                           con_form_account=con_form_account)


@main.route('/profile/delete_account', methods=['POST'])
@login_required
def delete_account():
    form = ChangePasswordForm(current_user.id, was_submitted=False)
    con_form_dataset = PasswordConfirmationForm(current_user.id, 'password_dataset', was_submitted=False)
    con_form_account = PasswordConfirmationForm(current_user.id, 'password_account')

    # Delete account password confirmation
    if con_form_account.validate_on_submit():
        delete_user_account(current_user)
        return redirect(url_for('main.index', info_modal_title="Account deleted",
                                info_modal_body="Your account has been deleted."))

    return render_template('profile.html', form=form, con_form_dataset=con_form_dataset,
                           con_form_account=con_form_account)


@main.route('/profile/quota')
@login_required
def quota():
    # Get datasets of the user
    owner = current_user.id
    return get_user_quota(owner)

app/templates/footer.html
<footer class="footer d-flex align-items-center justify-content-center">
    <div class="">
        This web service is offered by the
        <a href="http://www.dbda.cs.uni-frankfurt.de">Database Technologies and Data Analytics Group</a>
        (Institute of Computer Science, Goethe University Frankfurt)
    </div>
</footer>

app/templates/index.html
{%- extends "base.html" %}

{% block title %}Main{% endblock %}

{% block content %}
<div class="p-3 ms-5 me-5">
    <div class="rounded-3 p-5 mt-2 mb-4 titlebox">
        <h1 class="h1 ms-4 mt-4">ASDF-Dashboard</h1>
        <h1 class="h3 ms-4 mt-4">A web application for automatic and interactive clustering-based subgroup fairness
            analysis</h1>
    </div>

    {% if current_user.is_authenticated %}
    <h1 class="">Hello {{ current_user.name }}!</h1>
    {% endif %}
    <!-- Landing page (abstract, description, repository, paper) -->
    <div class="row mt-3 gx-3 gy-3">

        <div class="col col-4">
            <h1 class="h3">Abstract</h1>
            <p>
                The importance of an equal treatment of individuals by AI models drastically grows due to the demands of
                modern society. The potential discrimination or favoritism of specific groups of individuals is one of
                the common perspectives for the evaluation of model behavior. However, most of the available fairness
                tools require human intervention in the selection of subgroups of interest and therefore expert
                knowledge. In this paper we propose a new tool, the ASDF-Dashboard, which automates the process of
                subgroup fairness assessment. It automates the subgroup detection by applying a method based on
                unsupervised clustering algorithms and pattern extraction to ease the usage also for non-expert
                users.<br/>
                For further information on the scientific details and the experimental results see our paper
                <a href="https://doi.org/10.1007/978-3-031-15743-1_5">
                    Schäfer, J. & Wiese, L. (2022). Clustering-based Subgroup Detection for Automated Fairness Analysis.
                    <i>In European Conference on Advances in Databases and Information Systems</i>
                    (pp. 45-55). Springer, Cham.
                </a>
            </p>
        </div>
        <div class="col col-4">
            <h1 class="h3">Usage</h1>
            <p>
            <ul>
                <li>
                    <a href="{{ url_for('auth.register') }}">Register</a> your account
                </li>
                <li>Upload your datasets and classification results
                    <ul>
                        <li>csv-format</li>
                        <li>max. disk quota per user: 10MB</li>
                    </ul>
                </li>
                <li>Browse the data of your uploaded datasets</li>
                <li>Perform a subgroup fairness analysis of your trained classifier
                    <ul>
                        <li>Automated subgroup detection by clustering</li>
                        <li>Interactive visualization of fairness measures</li>
                        <li>Inspect the classifier behavior on individual subgroups</li>
                    </ul>
                </li>
            </ul>
            </p>
        </div>
        <div class="col col-4">
            <h1 class="h3">Project Repository</h1>
            <p>
                The ASDF-Dashboard is available open-source at
                <a href="https://github.com/jeschaef/ASDF-Dashboard">GitHub</a>. You can also install and deploy
                the application on your own machine as a self-hosted instance following the instructions given in the
                repository. For example, if you want to keep sensitive data on your machine or network or want to share
                the application to your team, a self-hosted instance would do the job. This way you can restrict access
                to the web service and, e.g., configure a different/unlimited disk quota.
            </p>
        </div>
    </div>


</div>

{% include 'footer.html' %}
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light navbar-bg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index')}}">
            <img src="{{ url_for('static', filename='logo.png') }}" alt="Logo" width="45" height="45">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ url_for('main.index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('dashboard.index') }}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.profile') }}">Profile</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-primary btn-margins" aria-current="page" href="{{ url_for('auth.logout')}}">
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-primary btn-margins" aria-current="page" href="{{ url_for('auth.login')}}">
                        Login
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-primary btn-margins" aria-current="page" href="{{ url_for('auth.register')}}">
                        Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

app/templates/profile.html
{%- extends "base.html" %}

<!-- Import form rendering macro -->
{% from '_formhelpers.html' import render_field %}

{% block styles %}
{{ super() }}
<style>
    .column {
        height: 100%;
    }
</style>
{% endblock %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="p-3 ms-5 me-5">
    <h1 class="h1">Hello {{ current_user.name }}</h1>

    <div class="row mt-3 gx-3 gy-3">

        <!-- Change password form + successful change modal -->
        <div class="col col-4">
            <div class="border rounded shadow p-2 column">
                <form method="POST" id="password-change-form"
                      action="{{ url_for('main.change_password') }}">
                    <h1 class="h5 ms-4 mb-4">Change password</h1>

                    {{ form.csrf_token() }}
                    <div class="row p-2 g-3 d-flex">
                        {{ render_field(form.old_password, form.is_submitted(), class='form-floating') }}
                        {{ render_field(form.new_password, form.is_submitted(), class='form-floating') }}
                        {{ render_field(form.confirm, form.is_submitted(), class='form-floating') }}
                        {{ form.submit(class="w-auto form-floating btn btn-lg btn-primary ms-auto me-auto")}}
                    </div>
                </form>
            </div>
        </div>

        <!-- Quota -->
        <div class="col col-4">
            <div class="border rounded shadow p-2 column">
                <h1 class="h5 ms-4 mb-4">Quota</h1>
                <canvas id="chart-quota"></canvas>
            </div>
        </div>

        <!-- Delete all uploaded datasets -->
        <div class="col col-4">
            <div class="border rounded shadow p-2 column">
                <div class="row p-2 g-4 d-flex">
                    <h1 class="h5 ms-4 mb-4">Delete All My Uploaded Datasets</h1>
                    <button type="button" class="btn btn-lg btn-danger w-auto ms-auto me-auto" id="delete-datasets"
                            data-bs-toggle="modal" data-bs-target="#confirm-delete-data">
                        <svg class="bi" width="20" height="20">
                            <use xlink:href="#trash-fill"></use>
                        </svg>
                        Delete My Datasets
                    </button>


                    <div class="modal fade" id="confirm-delete-data" tabindex="-1" aria-labelledby="cdd-label"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="cdd-label">Are you sure?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        Do you really want to delete your uploaded datasets?
                                    </p>
                                    <form method="POST" id="form-del-datasets"
                                          action="{{ url_for('main.delete_datasets') }}">
                                        <div class="form-floating w-75 ms-auto me-auto">
                                            {{ render_field(con_form_dataset.password, con_form_dataset.is_submitted(),
                                            class='form-floating') }}
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel
                                    </button>
                                    <button type="submit" class="btn btn-danger" form="form-del-datasets">
                                        <svg class="bi" width="16" height="16">
                                            <use xlink:href="#trash-fill"></use>
                                        </svg>
                                        Delete My Datasets
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h1 class="h5 ms-4 mb-4">Delete Account</h1>
                    <button type="button" class="btn btn-lg btn-danger w-auto ms-auto me-auto" id="delete-account"
                            data-bs-toggle="modal" data-bs-target="#confirm-delete-account">
                        <svg class="bi" width="20" height="20">
                            <use xlink:href="#trash-fill"></use>
                        </svg>
                        Delete My Account
                    </button>


                    <div class="modal fade" id="confirm-delete-account" tabindex="-1" aria-labelledby="cda-label"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="cda-label">Are you sure?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        Do you really want to delete your account?
                                    </p>
                                    <form method="POST" id="form-del-account"
                                          action="{{ url_for('main.delete_account') }}">
                                        <div class="form-floating w-75 ms-auto me-auto">
                                            {{ render_field(con_form_account.password, con_form_account.is_submitted(),
                                            class='form-floating') }}
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel
                                    </button>
                                    <button type="submit" class="btn btn-danger" form="form-del-account">
                                        <svg class="bi" width="16" height="16">
                                            <use xlink:href="#trash-fill"></use>
                                        </svg>
                                        Delete My Account
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

{% include 'footer.html' %}
{% endblock %}


{% block scripts %}
{{ super() }}
<script>
    const quota_url = JSON.parse('{{ url_for("main.quota") | tojson }}')
    const show_delete_dataset = JSON.parse('{{ con_form_dataset.is_submitted() | tojson }}')
    const show_delete_account = JSON.parse('{{ con_form_account.is_submitted() | tojson }}')
</script>
<script src="{{ url_for('static', filename='js/profile.js') }}"></script>
{% endblock %}